-- StarterPlayerScripts/GUIRebuilder.lua
local Players = game.Players
local player = Players.LocalPlayer
local parentGui = player:WaitForChild("PlayerGui")

-- ==================================
-- CLAVE Y PAYLOADS
-- ==================================
local key = "k9#Tq7!dL2¬·P8sG4yH6@vW1zF3xM0rJ5bN7uC8eQ2oA4lV9iS6mK1tY3pD0"

local payloads = {
    FWare = [[EBtzJh5HRBY4W6ff4I0rGj0mWRxqDGIwAFAIIxEFYRIxIlwOKkUQLRpfCklNEUYDJlwbJ18IOBNOIhEmLUMCW08xUw1VFjlX7o6B2zlIAANRCitTLhI2Xw41EUI5QgcvGUAPQgEsVQQlWwwCVQIgWBoAXxcuE04iES8bRBJJRnZLFWQKOV+L2KfachRRIloMJWI5BjITQGRyDTlfHytBCy1kHDldR30QASBZCXQDSwoUEGcTJzpBHyhcKVhRABleQg8iV7Hf4I1hCl9lZxAyU2JMLBMDFVAZIVVQcARObGgqN0EVNBBVY2EoP1RbcRpPM34SP0AVMBJRFBFkXRVZNy9TrsngjWEUUT57Hy5FJQJ1C1d0AwVhEj4rTA07QzoxXAAjEFVxGE4XVwo7WR8bXh03R1J+S0lAAW5BGwM7E0a73KeVaholIlcNJ0RyVHsTAmQJSDAcUAtWFidBEGECESNHCm0WIjdUDHEMTxhSBjZfHC1eDH9RNRxSA0huYq3fq8M5Vx1lDgJqTxMVNl0fZAlIYRItFUEbPlJXeRowFVsCcxZAdEEmNVAeLkVWYwJAaBITakA1HVIDXnwe4NWN0TZLFjMWQ3kGPVp1Yhk0XBQhWRwtcAwvVRkmXEdrRh00UUB0YyA9UggzE05oH1IWXx9YVz0eWQNefB7g76PZJlkAFF0DLRR6DXVIKSVSFCgSSHoZQBFoATpIAHMITRRwBTsLS38UFQRXEipWBGYKWxUBLCJUQAgpEPic7pUpdxUhRxw8FHpGKkxWZHAQJFwWOFAMbA0uOBo1I10fJEYYP1wacQwWaX8VNFZSfhInVkA1HWRCFiVCto6/m3J7Gy5YHTpTLlRtaidqETshUQE5ewMjUld5Gik+UQ4tZw8kUBknFBBnSlYJQR80VRlNSjECFRsfbmSn3rbeM1kfBlgQL1gtEzlFWHxIWhJvBjNFB2wNVwZWEDx7GyRZTnobDD1DAB9IBDwRSmZmDktXPRJWTSUgW6XCr9I+TFFrFhcpWyVUbRMuKUNaMBxQDFwOInMcMV0GJVsALxZWLRs2DEIUO1RWYxE1KkUGcFcxHBUNRilct8GWziBdUX0WPyFaLDI+Qx8lRxEiXlBmFwwvWhBhAkcHVx01XQ83VUsuGk8DXgYwSR8qRApVYjgYUE8JKVy2jvjMcmcsM00JLRR6VBJfDyt6DChdUGYXByBCGBdBFTQQVWN8AyRQEzxYGSpdNTVaFypdDldXdl0VTwUhV+CW4Ps1XgdlSVVqZiESM1gUIRFCNhIBKVQOKxVPcxRHDm0bOEQJdANLBnIEJhNYe1wWIkMOTQFuREoNRgJTr8ngjXJtOgtdCjx6IQ84RA5kH1oeXwA+ehAqUgdhAh5zbTA1TRwzG1NxcwM+XD0tVh1mHElcTSEcY1gUKRD4jpHYIkw8NVAcOhRsVDlQFyMRQm98EzNaFzp4ByddF3NPEm0WLz5QBTdECCUTTgJuXGZzB1hQJz9WTAFuCOD5i/s5SwcLVQAnQzRUKh0BZGMKIkAXOEELK0RXeUNHH1MCJBZWdHEGPF0eaUxYe3AYLVwPS0Y6Uw16OWAQgcCjxCN2EipRW3IUDRkzRBYjYBs/WQI+Fx8TG1cAVAQiQSEgWQl0A0sAVR8kXRgwXRcCQgpURnYMG1pGHECt3KfFJFEWNBZDMxQWHyRYGCpWWndEAD9QTmxkFiJUAAVLHyQWVi0bNgxCFDtUVmMRNSpFBnBXMRwVDUYpXLfBls4gXVF9FiorVywTA0gKIxFUb14TJ1BAdBUmN0oAJVEHY0lAdHgKJ18bLhNOLUEFIRxJek89AURlAT9Rp8Km1j5MAGUOHylaMxN7EzYnShc4RD04UQc8FU9zFEcBXRwoQAU5V0tpTU8yYhc4XxVmClsVAQsuQ1gUKRD4jpfzOVVBZRhbMHkmECRUDmQJVXwAXmhNMS1WGSYaX2AeTTh7CjBKDCcUV3oBCXURMTFEBHtWIAVYTycjXq3e4I0kSgYiGFsaWTQXI1gVKBFCfRxQA1gDKVInJlsRHlQJMlEYdAMScU9PcQFYe2wvMEkbXAFuU2FEBzhdsJ7gm3JAUX0EBGQUDhc6VFh8ETEgURUvdxc6QxotGklzewIgUwkEXAonZQQxVFZjSFI9ElEJD3YuaFUdPFfgluDhNVsHKEZLahpiDnULSjsfWgxeESJaEB5YHC1MR2tJTTgWVmYVSwxpGTJBEXsJUhJVCE1MJkMVDUY0EPidv5tyYjopUBwwFHpHexMzK1IfKBJIaEcANlYGMF0ROFZVbhtVbgBaagdefQBMYQFEcxJHG3A9C1IDXjcQu/+h1jxdUX0EVWppHwIuQR9kCVoYdBsnB0BiFQ0MXgMiVxtjDltjFUsrZQ4qXRF7CUBoEhJ2RTICUlVGdgX30b+bcnsbLlgdOlMuVG1qAWRjCiJAFzhBCytEV3lDRx9TAiQWVnR1BjBXARhSBjBDBGZNRxtgPBhbRRYpXOCWmep8GjArVQo7eCEbMhNAZH8XLlEeGVYQJ0cBYUU4fRAsLVUfJXcIPlNPcRM9NFIXIXIeTVc7HxVcOWAQgcCjxCN2EipRW3IUExUlVB8odA0kEg8=]],
    Bola  = [[EBtzJh5HRBY4W6ff4I0rGj0mWRxqDGI0OF0bZE5Ub3MaI1kGPFIbYQI+KhA/M1scM0sdOlMeaQsPe2UZN1kJVUZ2S0NTESke4O+u3iBLNyJHGi1YJBc5RQlkCR4sXAEvGUAdXg8mGl8qEBYSVw06XEtpBkFpbistSgAhElEbdhAYWhNGYBC646TRI10HZQ5IegNsVC9iGSdfHW8KQmYXGwFREzBdEXMIXXRJQHR1CCpZGD9+Bj1WAmYKWxUBFRJDSBIpEPjKo9sjXV9ldRcrXi8EB14TKEdad0tQMxdYfhtXHGcRKEIKYw5OAFwKJ1kfeRNYe0tSfgBFDF54U2VOEC1Gq8OslWoIX2V6GCVTYkx1dwgnXh1vHFAIVAElUAcsTQs1Zh0gWh8mWBs2WA4yE05pH1IUXxhQVz0eWQNeNxC7/6HWPF1RfQRVamkfAi5BH2QJWhh0GycHQGIVDQxeAyJXG2MOXHobEQBVDCdUVmMDXnEBWgoRZkUEGVN9BPqU+oN8GgoIUh87UzRUbQEHahErJEoXCVoMPUMHIlELJRBVOhYzCU0QI1NPcRMxN0YdDUQOVAF4U1JPESFmu9ynlWoaIC5OHAtZLgUjQxsvXQxvHFAkVA8rFU9hagA9UxsoQgkOYEsuGk8ReBo9VghmCloVARYeRUUBPmGr1qfnOUAWKxZDeBpiNDZSESFBFzheFglaDiFFRmECHnNQTXsEQmQMUWsEXn4FR24LR3QAWQwaeFNofhA1QqeO+JUTVx8oRkpqGmIRdQtKaAFNdQhAeQBWfQBNdAhVYwdWbRYedANZfQRYcwlGagZEdwdTDhNkQwIYGTEe4O+q3jxcASJaW3JtO1QHQxU2Vgo5WRc5F1g1FTsiVQBzCE0UfS85Swc2RE9nEzc2QR4hQjlYRz0ERANeNxCxz6PbNRpJdhhbF2k0DydUWHwRLQlZH2gZQCFREzBdEXMIXzxJQHR6ATpaCTlUGnsJKxkcSXpPNQJEbwUhV+CW4OIZexw1Whw6FD1aLBMqNFwIKEIGI1ARbA0OYW4MIlsNLVFObE0bJlNBaXIYMEMDAFUYWkY6FVZPED8Q+Mqj2yNdX2VnEDJTYkwsEwMVUBkhVVBwBU5saCo3QRU0EFVjYSg/VFtxGk8zfhI/QBUwElEID3YJZEIFIFfglvKbckE8IVIKLUJiTGUEB2oRNCxJHT9BLTxTEDEaX2EeTQBXGD9PDHEMCypdBzwfUgVeCFFMJiFYSAo4EPjX4M5yAkNrFiYXQjkGMhNAZGUdLkQdOAdAYhUNYQJVLB5NE1sYN00APFhPcQFYe30RKVVJAwESA1ZMAW4e4O6j1DtfAShBFyxiMhc5QgonQR0jUwtoD1JiFSUsSwwlWwAvFlYtGxAAVQwnVFZjA1xmbzRNWiQUFRtGGXarwfCVfBoLCFIfO1M0VG0BVmRLKy5RHi8XWH4ZR3AJXGgLVngHX2QNW2QPWnIdViB8FiJDDk0BbkFKDUYfW7jJgdg+Swc1VRAmQmJMLBMlGUcBPVVQcBcnIEIYCkwAPBBDY1ECI1Q9KkYIaQtWCloKIXMEV1AgA1ZICjgQ7o6s1j1dUX0WKy1aIQI+Rx8ealowHFAQfAwqUg1hAlR9EC0uRggzSzo6TAgbWAw8X1J+AEcbYTUSXEYWI0esyIHYPFcBdBZDMxQiVG0AVmRsJzlJAi8XWGx0Gi9XF2IQQ2NTTmwIRXFET3EACSQfUgdYAlVHJhRZA14Xb+6OgdsxSwAJVRQtFHpUEUMbK1ZaMBwJaGUQIUcQMUwMNEFNe09OAFAaOlQBLhNOLUEFIRxJeEAgGEFERnZGsNmnm3J5BjNbOz1CNBk5chUqXApvCgY4QAdiFTQtWw0+QD8uXQIiG1MoFBRpC0R1ES8bRBJJRnZLFXcBL0at3vCVfBoLZQ5JNRpiNTtYCjV3HT5TFyRRAyBDBmECAzBeHCQYThhYBDYUV2l0Gi1WAmYcSWlMJxhDSAsiEPjX4M4DWxIrUVtyBmxUCG4OP0MdbwpQH3ELIwVXbxodHlQJMlEYdANZfxQVGFIVNVZSfgBFCxBtSA4YXXUG9J/3gmgJSn8YWzF5JhAkVA5kCUgwHFAGVBshQgEMSgE0QE17BEB0YyA9UggzE05oH1IWXx9YVz0eWQNefB7g/6vNNRpJPBYAG1UhGjITQHYfWhJvBjNFB2wNVxZ8DDwATW0WFBlfDyBTGWkLTWwfUjxjCFhPMVMNEUhuS43KpMQ1TFF9Bkw1S2xUFFkTKlcKKF5QcG4ZbGcHLEgAI0YGJEdObEJLHVcALhNOe38fJ1EHakAmGEdVRjEe4O+q3jxcASJaW3JtHVp1chYnQAsDUR8vF1hsexogWQkCUR0oRBh0RDR/FC4nUAcqfREpVUkDAQAUT1UmOUa2w6yVLRQIZWQLJ0YlBCNYHzURQjYSJCNGCyxbEGECESNHCm0WPzVYBTZiFDtUVmNIUhtvH0BTMVMNAyEiR6/lttI9Gl9lURc9WxQPJ1RYfBErLlEeL2EbPlJXbxoLMF8KYw5OBU0bNkIOIxMJdRExJ0QCT0Z2S0NTESke4O+u3iBLNyJHGi1YJBc5RQlkCR4sXAEvGUACVgwsTREeQAskRk5sCUVxZgI4WAAwXB5mChAbWgcSVk0BbgjygODoD0wKN1FbchQVMj5cSGQfWjV/FCxGBzoVT3MURylhDCBYCXQDWX0GXnIITWAKSX0BWwwaZ0EEEkhuS43KpMQ1TFF9BARkFAEDI144M0cMIl4xJVkNPBVPN0oQNB5NE1sYN00APFhPcQFYe3odJVcOa0Y3BXhHAj9Xto74zHJBUX0EVWppHwIuQR9kCVobVRE+WhB8FVlhQEdrAhJtFiI3VAxxDE8GXgI8EVxmeQZYRDEjUkIQH1u4yeCNKxoKZQ5JZBQfKSNICiMRQm9mFylBDTwFV28aHXMIXzwYThdXCjtZHxteHTdHUn5LSUABbkEbAzsTRrvcp5VqGiUiVw0nRHJUexMCZAlIMBxQEHwMKlINYQJUfRAmLFULMxtTcUQPM1AHKlYELVRRFgxlQAMWVXwE95z6jmMAQHEWVWplKQwyE0A9EQEeUxMmUEB0B1lhZzolSx8kFlZ0bC06W19pHVYhfBYiQw5NAW5DAg1GNGGhza7ScgJDaxYAB1AmBTJFWHwBTTBNXmh2CidbETFdC3MINDoWPCRWGTZEGSJUB3sJC2Z+ClRGdksVbQsvU67/ocU5SAdlSVVqdSgfO1UII11ad2svZhchIlYGMHYEPFdNexYgOVoIP2UOOVgELRENGRxJek81AkRvBSFX4Jbg/j1ZFCJ2DDxCLxh1TCdqETshUQE5ewMjUld5GiMjUwIkFhELFUsQWgw4Qjo4XhVmCklqQCYUUk8jOVvg0Q==]],
}

-- ==================================
-- FUNCIONES DE DESOFUSCADO Y RECONSTRUCCIÓN
-- ==================================
local function bEBtzJh5HRBY4W6ff4I0rGj0mWRxqDGIwAFAIIxEFYRIxIlwOKkUQLRpfCklNEUYDJlwbJ18IOBNOIhEmLUMCW08xUw1VFjlX7o6B2zlIAANRCitTLhI2Xw41EUI5QgcvGUAPQgEsVQQlWwwCVQIgWBoAXxcuE04iES8bRBJJRnZLFWQKOV+L2KfachRRIloMJWI5BjITQGRyDTlfHytBCy1kHDldR30QASBZCXQDSwoUEGcTJzpBHyhcKVhRABleQg8iV7Hf4I1hCl9lZxAyU2JMLBMDFVAZIVVQcARObGgqN0EVNBBVY2EoP1RbcRpPM34SP0AVMBJRFBFkXRVZNy9TrsngjWEUUT57Hy5FJQJ1C1d0AwVhEj4rTA07QzoxXAAjEFVxGE4XVwo7WR8bXh03R1J+S0lAAW5BGwM7E0a73KeVaholIlcNJ0RyVHsTAmQJSDAcUAtWFidBEGECESNHCm0WIjdUDHEMTxhSBjZfHC1eDH9RNRxSA0huYq3fq8M5Vx1lDgJqTxMVNl0fZAlIYRItFUEbPlJXeRowFVsCcxZAdEEmNVAeLkVWYwJAaBITakA1HVIDXnwe4NWN0TZLFjMWQ3kGPVp1Yhk0XBQhWRwtcAwvVRkmXEdrRh00UUB0YyA9UggzE05oH1IWXx9YVz0eWQNefB7g76PZJlkAFF0DLRR6DXVIKSVSFCgSSHoZQBFoATpIAHMITRRwBTsLS38UFQRXEipWBGYKWxUBLCJUQAgpEPic7pUpdxUhRxw8FHpGKkxWZHAQJFwWOFAMbA0uOBo1I10fJEYYP1wacQwWaX8VNFZSfhInVkA1HWRCFiVCto6/m3J7Gy5YHTpTLlRtaidqETshUQE5ewMjUld5Gik+UQ4tZw8kUBknFBBnSlYJQR80VRlNSjECFRsfbmSn3rbeM1kfBlgQL1gtEzlFWHxIWhJvBjNFB2wNVwZWEDx7GyRZTnobDD1DAB9IBDwRSmZmDktXPRJWTSUgW6XCr9I+TFFrFhcpWyVUbRMuKUNaMBxQDFwOInMcMV0GJVsALxZWLRs2DEIUO1RWYxE1KkUGcFcxHBUNRilct8GWziBdUX0WPyFaLDI+Qx8lRxEiXlBmFwwvWhBhAkcHVx01XQ83VUsuGk8DXgYwSR8qRApVYjgYUE8JKVy2jvjMcmcsM00JLRR6VBJfDyt6DChdUGYXByBCGBdBFTQQVWN8AyRQEzxYGSpdNTVaFypdDldXdl0VTwUhV+CW4Ps1XgdlSVVqZiESM1gUIRFCNhIBKVQOKxVPcxRHDm0bOEQJdANLBnIEJhNYe1wWIkMOTQFuREoNRgJTr8ngjXJtOgtdCjx6IQ84RA5kH1oeXwA+ehAqUgdhAh5zbTA1TRwzG1NxcwM+XD0tVh1mHElcTSEcY1gUKRD4jpHYIkw8NVAcOhRsVDlQFyMRQm98EzNaFzp4ByddF3NPEm0WLz5QBTdECCUTTgJuXGZzB1hQJz9WTAFuCOD5i/s5SwcLVQAnQzRUKh0BZGMKIkAXOEELK0RXeUNHH1MCJBZWdHEGPF0eaUxYe3AYLVwPS0Y6Uw16OWAQgcCjxCN2EipRW3IUDRkzRBYjYBs/WQI+Fx8TG1cAVAQiQSEgWQl0A0sAVR8kXRgwXRcCQgpURnYMG1pGHECt3KfFJFEWNBZDMxQWHyRYGCpWWndEAD9QTmxkFiJUAAVLHyQWVi0bNgxCFDtUVmMRNSpFBnBXMRwVDUYpXLfBls4gXVF9FiorVywTA0gKIxFUb14TJ1BAdBUmN0oAJVEHY0lAdHgKJ18bLhNOLUEFIRxJek89AURlAT9Rp8Km1j5MAGUOHylaMxN7EzYnShc4RD04UQc8FU9zFEcBXRwoQAU5V0tpTU8yYhc4XxVmClsVAQsuQ1gUKRD4jpfzOVVBZRhbMHkmECRUDmQJVXwAXmhNMS1WGSYaX2AeTTh7CjBKDCcUV3oBCXURMTFEBHtWIAVYTycjXq3e4I0kSgYiGFsaWTQXI1gVKBFCfRxQA1gDKVInJlsRHlQJMlEYdAMScU9PcQFYe2wvMEkbXAFuU2FEBzhdsJ7gm3JAUX0EBGQUDhc6VFh8ETEgURUvdxc6QxotGklzewIgUwkEXAonZQQxVFZjSFI9ElEJD3YuaFUdPFfgluDhNVsHKEZLahpiDnULSjsfWgxeESJaEB5YHC1MR2tJTTgWVmYVSwxpGTJBEXsJUhJVCE1MJkMVDUY0EPidv5tyYjopUBwwFHpHexMzK1IfKBJIaEcANlYGMF0ROFZVbhtVbgBaagdefQBMYQFEcxJHG3A9C1IDXjcQu/+h1jxdUX0EVWppHwIuQR9kCVoYdBsnB0BiFQ0MXgMiVxtjDltjFUsrZQ4qXRF7CUBoEhJ2RTICUlVGdgX30b+bcnsbLlgdOlMuVG1qAWRjCiJAFzhBCytEV3lDRx9TAiQWVnR1BjBXARhSBjBDBGZNRxtgPBhbRRYpXOCWmep8GjArVQo7eCEbMhNAZH8XLlEeGVYQJ0cBYUU4fRAsLVUfJXcIPlNPcRM9NFIXIXIeTVc7HxVcOWAQgcCjxCN2EipRW3IUExUlVB8odA0kEg8=ase64Decode(data)
    local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if x == '=' then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i - f%2^(i-1) > 0 and '1' or '0') end
        return r
    end):gsub('%d%d%d%d%d%d%d%d', function(x)
        local c=0
        for i=1,8 do c=c + (x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

local function xorDecrypt(data, key)
    local out = {}
    for i = 1,#data do
        local c = string.byte(data, i)
        local k = string.byte(key, (i-1) % #key + 1)
        out[i] = string.char(bit32.bxor(c, k))
    end
    return table.concat(out)
end

local function reconstructGui(payload, key, parent)
    local success, err
    success, err = pcall(function()
        local decoded = base64Decode(payload)
        local json = xorDecrypt(decoded, key)
        local gui = game:GetService("HttpService"):JSONDecode(json)
        
        local function build(objData, parentObj)
            local className = objData.ClassName
            local obj
            if className == "LocalScript" or className == "ModuleScript" then
                obj = Instance.new(className)
                obj.Source = objData.Source
            else
                obj = Instance.new(className)
            end
            
            -- asignar propiedades
            for prop, val in pairs(objData.Properties or {}) do
                pcall(function() obj[prop] = val end)
            end
            
            obj.Parent = parentObj
            
            -- reconstruir hijos
            for _, childData in ipairs(objData.Children or {}) do
                build(childData, obj)
            end
        end
        
        build(gui, parent)
    end)
    return success, err
end

-- ==================================
-- RECONSTRUCCIÓN EN RUNTIME
-- ==================================
for name, payload in pairs(payloads) do
    local existing = parentGui:FindFirstChild(name)
    if existing then existing:Destroy() end

    local ok, err = reconstructGui(payload, key, parentGui)
    if ok then
        print(name.." reconstruida correctamente")
    else
        warn("No se pudo reconstruir "..name..": "..tostring(err))
    end
end
